### ISSUE TITLE
Does not detect files if extension is all caps

### ISSUE THREAD

**Issue by ngoomie** [CaligulaCa3sar/cbz-create#2]
If you attempt to use cbz-create on a folder with files in an acceptable format but with extensions in all caps, it does not detect any valid files due to file extension matching being case-sensitive

I don't know if this repo will be updated to fix this issue because the owner hasn't commit any changes to any of their repos in some time, so a quick fix I did for anyone else who stumbles upon this while having this problem is to somehow mass-rename the files to either change the file extension to all lower case, or just append the same file extension in locaps to the end of the files. I did the second using the following bash script:
`for file in *; do mv -- "$file" "$file.jpg"; done`
The two file extensions thing is ugly, but considering I imagine most people who are going to be using this plan on deleting the original files afterwards anyways, it's not really a problem. Obviously you're going to want to replace 'jpg' with whatever extension matches in your situation.

**Comment by CaligulaCa3sar** [comment]
Thank you very much for bringing this to my attention.  You're quite right, I had completely overlooked something so obvious.

I have bodged a workaround by moving the list of extensions out into a separate variable which can be tailored by the user and then amended the function to concatenate the original string of extensions with an upper-case version of itself and then globbing the result.

Thanks again and I hope this solves the problem to your satisfaction.

**Comment by ngoomie** [comment]
Thank you very much! This definitely solves it.
